---
title: "Data Import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl) # library to read excel
```

## Read in some data

read in the litters dataset.
```{r}
litters_df = read_csv("./data/FAS_litters.csv")
# "./" starting from the r. project folder 

litters_df = janitor::clean_names(litters_df)
#把原来表头的特殊符号都去掉了 / 从janitor这个package中用clean_names这个code

```

##  Take a look at the data

printing in the console.

```{r}
litters_df

```

```{r}
tail(litters_df)
```


```{r}
# check the missing value/mean / histogram/ distribution
skimr::skim(litters_df)
```


## Options to read_csv

check out '?read_csv" for more information 
```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE)
litters_df = read_csv("./data/FAS_litters.csv", na = c("", "NA", 999))

```

## other file formats

read in an excel file.
```{r}
library(readxl) # library to read excel
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
#"./"--> starting from the project folder 

```

Read in a SAS file.

```{r}
library(haven) # library to read SAS
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

## comparison with Base R

what about 'read.csv' .. ?
read_csv vs. read.csv (use read_csv--> better)

```{r}
litters_base = read.csv("./data/FAS_litters.csv")
litters_readr = read_csv("./data/FAS_litters.csv") #better

litters_base # show all results--> difficult to read
litters_readr # easy to read 
```

## Exporting data

Export the mlb sub_table.
```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv")

```

