---
title: "Data Tidying"
output: github_document
---
# load package
```{r}
library(tidyverse) # tidyverse is a range of packages


options(tibble.print_min = 5)

```


# pivot_longer

load the dataset

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()

pulse_df
```

wide format to long format...

```{r}
pulse_tidy_data = 
  pivot_longer(
    pulse_df, #dataset
    bdi_score_bl:bdi_score_12m, #column range
    names_to = "visit", #new column name
    values_to = "bdi") # value

pulse_tidy_data
```

去掉“vist”值的前缀 remove prefix

```{r}
pulse_tidy_data = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_", #remove prefix
    values_to = "bdi")

pulse_tidy_data
```

## using $>$ 
rewrite, combine, and extend(to add a mutate)
```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% #load dataset
  janitor::clean_names() %>%  # clean dataset
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>% #For tidying single tables
  relocate(visit) %>% #list "visit" to be the first column
  mutate(
    visit = replace(visit, visit == "bl", "00m"), # replace the value "bl" by "00m" in "visit" column
    visit = factor(visit)) %>% # turns "visit" into factor
  arrange(id, visit) #arrange by "id" and "visit"

print(pulse_df, n = 12) #print the dataset with 12 rows
```

```{r, show_col_types = FALSE}

litters_wide = 
  read_csv("./data/FAS_litters.csv", show_col_types = FALSE) %>%
  janitor::clean_names()
litters_wide

litters_wide = 
  read_csv("./data/FAS_litters.csv", show_col_types = FALSE) %>%
  janitor::clean_names()%>%
  select(litter_number, ends_with("weight")) %>% 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight") %>% 
  mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
litters_wide
```

# pivot_wider

make up some data

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

analysis_result

```

long format to wide format
```{r}
pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")
```

# Binding rows

import data
```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")
fellowship_ring

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```

 stack datasets together
```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "gender", #character vectors
    values_to = "words") %>% #numberic vectors
  mutate(race = str_to_lower(race)) %>% #全换成小写
  select(movie, everything()) #movie在第一列但保留其他columns

lotr_tidy
```
 
